services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - 'POSTGRES_DB=ems-database'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
